name: SQL Syntax Check

on:
  pull_request:
    paths:
      - 'db.sql'

jobs:
  syntax_check:
    name: Check SQL Syntax
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Wait for MariaDB to Initialize
      run: |
        until docker exec mysql mysqladmin ping &> /dev/null; do
          echo "Waiting for MariaDB to initialize..."
          sleep 5
        done

    - name: Run SQL Linting
      run: |
        docker exec mysql mysql -h localhost -P 3306 -u root -p"${{ secrets.DB_PASSWORD }}" < db.sql
