name: SQL Syntax Check

on:
  pull_request:
    paths:
      - 'db.sql'

jobs:
  syntax_check:
    name: Check SQL Syntax
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MARIADB_USER: user
          MARIADB_PASSWORD: password
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Wait for MariaDB to Start
        run: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      - name: Run SQL Linting
        run: |
          password="${{ secrets.MYSQL_ROOT_PASSWORD }}"
          docker exec -i mariadb mysql -uuser -ppassword < db.sql

      - name: Stop MariaDB
        run: docker stop mariadb
