name: SQL Syntax Check

on:
  pull_request:
    paths:
      - 'db.sql'

jobs:
  syntax_check:
    name: Check SQL Syntax
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up MariaDB
      uses: montudor/action-mysql@v1
      with:
        mysql-version: '10.6'
        root-password: ${{ secrets.DB_PASSWORD }}

    - name: Wait for MariaDB to Start
      run: sleep 10

    - name: Get MariaDB Container IP
      run: echo "::set-env name=MARIADB_IP::$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql)"

    - name: Run SQL Linting
      run: |
        docker exec mysql mysql -h ${{ env.MARIADB_IP }} -P 3306 -u root -p"${{ secrets.DB_PASSWORD }}" < db.sql

    - name: Stop MariaDB
      run: docker stop mysql
