name: SQL Syntax Check

on:
  pull_request:
    paths:
      - 'db.sql'

jobs:
  syntax_check:
    name: Check SQL Syntax
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: itflowdb
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run SQL Linting
        run: mysql --host 127.0.0.1 -uuser -ppassword itflowdb < db.sql

      - name: Stop MariaDB
        run: docker stop mariadb
