name: SQL Syntax Check

on:
  pull_request:
    paths:
      - 'db.sql'

jobs:
  syntax_check:
    name: Check SQL Syntax
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Wait for MariaDB to Start
      run: dockerize -wait tcp://localhost:3306 -timeout 1m

    - name: Run SQL Linting
      run: |
        docker exec -i mariadb mysql -uroot -p"${{ secrets.DB_PASSWORD }}" < db.sql

    - name: Stop MariaDB
      run: docker stop mariadb
