name: SQL Syntax Check

on:
  pull_request:
    paths:
      - 'db.sql'

jobs:
  generate_init_sql:
    name: Generate init.sql
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate init.sql
        run: |
          mkdir -p init
          echo "DELETE FROM mysql.proxies_priv WHERE Host != 'localhost';" > init/init.sql
          echo "Generated init.sql at: ${{ github.workspace }}/init/init.sql"  # Output file path

      - name: Upload init.sql artifact
        uses: actions/upload-artifact@v2
        with:
          name: init-sql
          path: init/init.sql

  syntax_check:
    name: Check SQL Syntax
    runs-on: ubuntu-latest
    needs: generate_init_sql

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download init.sql artifact
        uses: actions/download-artifact@v2
        with:
          name: init-sql
          path: init

      - name: Wait for MariaDB to Start
        run: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      - name: Run SQL Linting
        run: |
          password="${{ secrets.MYSQL_ROOT_PASSWORD }}"
          docker run --rm -v ${{ github.workspace }}/init:/docker-entrypoint-initdb.d -e MYSQL_ROOT_PASSWORD=$password mariadb:latest mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/init.sql
